commit-msg:
  commands:
    commitlint:
      skip: [merge, rebase]
      run: node ./node_modules/@commitlint/cli/cli.js --edit {1}

pre-commit:
  parallel: true
  commands:
    eslint:
      glob: '*.{js,ts,json,json5,jsonc,yml,yaml,md}'
      skip: [merge, rebase]
      run: yarn eslint {staged_files} --fix
      stage_fixed: true
    stylelint:
      glob: '*.{css,scss}'
      skip: [merge, rebase]
      run: yarn stylelint {staged_files} --fix --allow-empty-input --quiet-deprecation-warnings
      stage_fixed: true
