name: Playground

on:
  push:
    branches: [master]
    paths:
      - docs/**
  workflow_dispatch: {}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build docs
        run: yarn docs:build

      - name: Publish to GH pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
