name: Release

on:
  push:
    tags: [v*]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Getting latest changelog entry
        uses: actions/github-script@v7
        id: latest-changelog-entry
        with:
          result-encoding: string
          script: |
            const extractLatestChangelogEntry = require('./.github/extract-latest-changelog-entry.cjs');
            return extractLatestChangelogEntry();

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{steps.latest-changelog-entry.outputs.result}}

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.morev.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.morev.npmAlwaysAuth true
          yarn config set npmScopes.morev.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: yarn npm publish --access public
